### ISSUE TITLE
Fibonacci test fails

### ISSUE THREAD

**Issue by tinybike** [thinkloop/memoizerific#1]
Just FYI.

```
(master) jack@vent:~/src/memoizerific$ npm test

> memoizerific@1.5.2 test /home/jack/src/memoizerific
> npm run -s test:map && npm run -s test:similar

Started
.......F.......

Failures:
1) fibonacci should have significantly higher performance (try rerunning)
  Message:
    Expected false to equal true.
  Stack:
    Error: Expected false to equal true.
        at Object.<anonymous> (/home/jack/src/memoizerific/tests/fibonacci.js:40:137)

15 specs, 1 failure
Finished in 0.02 seconds
npm ERR! Test failed.  See above for more details.
```

(Tried re-running a couple times; same result.)

**Comment by thinkloop** [comment]
This is an interesting one, and I wonder if you have any good thoughts on
this. Basically that test is a catch-all sanity check that the memoization
is working by being "significantly more performant" than its non-memoized
counterpart. The test runs raw fibonacci and then memoized fibonacci,
then checks that the memoized fibonacci is an arbitrary 2s faster than the
non-memoized one. It never fails on my machine, but of course this is
highly dependent on the hardware, and other environment-specific
things. Perhaps instead of hard-coding 2s I should look for a multiple,
like 5x faster - what do you think?

**Comment by tinybike** [comment]
Yeah, I think a multiple would be better.  The multiple might still be different depending on environment, but at least it's an apples-to-apples comparison.

**Comment by thinkloop** [comment]
I updated the test to be a multiple, mind letting me know if it works for you now?

**Comment by tinybike** [comment]
Yep, it works now!
