### ISSUE TITLE
Function called with two arguments throws error when previous call was with one argument

### ISSUE THREAD

**Issue by priecint** [thinkloop/memoizerific#3]
`memoizerific.js:25 Uncaught TypeError: currentCache.has is not a function` is thrown in following case:

```
const testFn = memoizerific(100)((param, anotherParam) => {
    return param;
});

testFn("some value");
testFn("some value", "yet another"); // throws here
```

This doesn't happen with 2-param-and-then-3-param calls. Using second param (`undefined` suffices) in first call works OK.

**Comment by thinkloop** [comment]
Thanks for the report.

Since this is a performance-sensitive lib, instead of adding logic to compensate for differing numbers of arguments, I decided to throw an error explaining the situation:

`throw new Error('Memoizerific functions should always be called with the same number of arguments');`

Let me know if this is problematic for you.
