### ISSUE TITLE
Default props are not recognized

### ISSUE THREAD

**Issue by newyork-anthonyng** [thinkloop/memoizerific#8]
Related to issue #3. 
Functions with default parameters are throwing Errors when used with and without defaults. Is this the intended behavior?

```js
function greet(name, greeting = 'Hi') {
  console.log(`${greeting} ${name}`);
}

const memoizedGreet = memoizerific(100)(greet);

memoizedGreet('Anthony'); // arguments.length = 1
memoizedGreet('Paul', 'Yo');  // arguments.length = 2; throws Error
```

**Comment by thinkloop** [comment]
Hey,

Are you transpiling with babel? Babel removes default params from the function signature and processes them in the body, like this:

```
// 2 params
function fn1(a, b=1) {
}
```

becomes:

```
// 1 param
function fn1(a) {
  var b = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 1;
}
```

The function ends up having a signature of one param. Allowing that through without throwing an error would cause unexpected results because the code would look like a param is being passed in, but memoizerific would receive `undefined`, returning the result related to that instead of the passed in param. The only proper resolution will be when default params are used natively. As a workaround, I believe you can pass `undefined` for the default params. Or, handle defaults manually:

```
function fn1(a, b) {
  var b = arguments[1] !== undefined ? arguments[1] : {default value here};
}
```

Let me know!

**Comment by thinkloop** [comment]
updated previous comment

**Comment by newyork-anthonyng** [comment]
@thinkloop

Yes, I'll have to do some refactor on my part. Thanks for the response 👍
